Add ICLR 2019, 2018
Marcus9512/dd2430 pull request #18
Opened 2020-09-24 09:47 UTC by loalm

2020-09-24 09:54 UTC, loalm commented
All available papers from ICLR with a decision seem to be added now. 2016, 2017 seem unavailable. 2014, 2013 papers have no decisions.

2020-09-24 12:51 UTC, JonasRSV commented
Hey, I know that atleast for ICLR 2019  the decision notes does not contain the "decision" field. I started working on fixing so that the is_accept heuristic works for 2019 as well by using the rating field. But I am not sure that that code is correct yet, nor am I sure it works for 2018.

Did you make sure that it works correctly for 2018 and 2019? If not please do that first :)

2020-09-24 12:51 UTC, JonasRSV requested changes
See previous comment.

2020-09-25 10:20 UTC, loalm commented
@JonasRSV I changed the decision_notes for ICLR 2018 and ICLR 2019 + changed some parts of the accept heuristic. Could you take a look at this? :)

2020-09-25 11:33 UTC, JonasRSV requested changes

2020-09-25 11:33 UTC, JonasRSV commented on src/Tools/open_review_downloader.py
> +        # Commented this out, not sure if this is needed anymore
You can remove this if it is not used anymore :)

2020-09-25 11:33 UTC, JonasRSV commented on src/Tools/open_review_downloader.py
> +        #Works for ICLR 2019
Does it also work for 2018?

2020-09-25 11:33 UTC, JonasRSV commented on src/Tools/open_review_downloader.py
> +    ##### WORKSHOPS
Nice!

2020-09-25 11:34 UTC, JonasRSV commented
Looks great! Once you have removed that un-commented code and answered weather it works for 2018 also, ping me again and i'll approve it! :)

2020-09-25 12:04 UTC, loalm commented
@JonasRSV Great, I have removed the unused part of the accept heuristic. As for ICLR 2018, the accept heuristic works similarly as with MIDL.

2020-09-25 12:38 UTC, JonasRSV approved these changes

2020-09-25 12:38 UTC, JonasRSV commented
Looks good! Feel free to merge :)

2020-09-28 08:09 UTC, merged